name: Run Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Установка .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Восстановление зависимостей
        run: dotnet restore

      - name: Сборка проекта
        run: dotnet build --no-restore --configuration Release

      - name: Запуск тестов
        run: dotnet test --no-build --configuration Release --logger trx --results-directory TestResults  
